FROM quay.io/pypa/manylinux_2_28_x86_64

RUN dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-rhel8.repo \
    && dnf install -y cuda-toolkit-12-8 \
    && dnf clean all
