// Copyright (c) Meta Platforms, Inc. and affiliates.

// Moodist API versioning - generated values for version checking

#pragma once

#include <cstdint>

namespace moodist {

// API version - increment when struct layout changes
constexpr uint32_t kMoodistAPIVersion = 1;

// Build magic - changes per build to catch mismatched libraries
// This is generated by CMake (random value at configure time)
#ifndef MOODIST_BUILD_MAGIC
#define MOODIST_BUILD_MAGIC 0x0000000000000000ULL  // Default for development
#endif

constexpr uint64_t kMoodistBuildMagic = MOODIST_BUILD_MAGIC;

} // namespace moodist
