# A workflow that uses a Github actions GPU runner and builds the project
name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: [ubuntu-latest-gpu]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install torch torchvision torchaudio
      - name: Build and test
        run: |
          pip3 install -e .
          # Run tests
          # pytest --maxfail=1 --disable-warnings -q